# set the kernel to use
FROM python:3.10-alpine

# set the working directory
#WORKDIR /Users/caterinamarchetti/politecnico/IoT/Project/catalog_fin

# copy the requirements file
COPY requirements.txt ./
# install the needed requirements
RUN pip3 install -r requirements.txt
# copy all the files in the container
COPY catalog7.json ./
COPY catalog_7.3.py ./
# the command that will be executed when the container will start
CMD ["python3","./catalog_7.3.py"]