# set the kernel to use
FROM python:3.10-alpine

# set the working directory
#WORKDIR /Users/caterinamarchetti/politecnico/IoT/Project/telegram

# copy the requirements file
COPY requirements.txt ./
# install the needed requirements
RUN pip3 install -r requirements.txt
# copy all the files in the container
COPY configuration_telegram.json ./
COPY TelegramBot6.py ./
COPY MyMQTT.py ./
# the command that will be executed when the container will start
CMD ["python3","./TelegramBot6.py"]